### ISSUE TITLE
docker compose build  error on Frontend ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by bafraikin** [pwndoc/pwndoc#405] opened 2022-11-22 12:52 UTC
```
$ quasar build

 Build mode........ spa
 Pkg quasar........ v1.22.2
 Pkg @quasar/app... v2.4.3
 Debugging......... no
 Publishing........ no

 Configured browser support (at least 87.47% of global marketshare):
 · Chrome for Android >= 107
 · Firefox for Android >= 106
 · QQ for Android >= 13.1
 · UC for Android >= 13.4
 · Android >= 107
 · Baidu >= 13.18
 · Bb >= 7
 · Chrome >= 105
 · Edge >= 106
 · Firefox >= 105
 · IE >= 11
 · IE Mobile >= 10
 · iOS >= 15.6
 · Kaios >= 2.5
 · Opera Mini >= all
 · Opera Mobile >= 12.1
 · Opera >= 91
 · Safari >= 15.6
 · Samsung >= 18.0

 App · Reading quasar.conf.js
 App · Transpiling JS (Babel active) - includes IE11 support
 App · Extending SPA Webpack config
 App · Cleaned build artifact: "/home/bapt/Desktop/tools/pwndoc/frontend/dist/spa"
 App · Generating Webpack entry point
 App · Compiling with Webpack...

 • Compiling:
 └── SPA █                    0% compiling

  Error: error:0308010C:digital envelope routines::unsupported
  
  - hash:67 new Hash
    node:internal/crypto/hash:67:19
  
  - node:crypto:130 Object.createHash
    node:crypto:130:10
  
  - createHash.js:135 module.exports
    [frontend]/[webpack]/lib/util/createHash.js:135:53
  
  - NormalModule.js:417 NormalModule._initBuildHash
    [frontend]/[webpack]/lib/NormalModule.js:417:16
  
  - NormalModule.js:471 handleParseError
    [frontend]/[webpack]/lib/NormalModule.js:471:10
  
  - NormalModule.js:503 
    [frontend]/[webpack]/lib/NormalModule.js:503:5
  
  - NormalModule.js:358 
    [frontend]/[webpack]/lib/NormalModule.js:358:12
  
  - LoaderRunner.js:373 
    [frontend]/[loader-runner]/lib/LoaderRunner.js:373:3
  
  - LoaderRunner.js:214 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:214:10
  
  - LoaderRunner.js:221 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:221:10
  
  - LoaderRunner.js:236 
    [frontend]/[loader-runner]/lib/LoaderRunner.js:236:3
  
  - LoaderRunner.js:130 runSyncOrAsync
    [frontend]/[loader-runner]/lib/LoaderRunner.js:130:11
  
  - LoaderRunner.js:232 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:232:2
  
  - LoaderRunner.js:205 Array.<anonymous>
    [frontend]/[loader-runner]/lib/LoaderRunner.js:205:4
  
  - CachedInputFileSystem.js:55 Storage.finished
    [frontend]/[enhanced-resolve]/lib/CachedInputFileSystem.js:55:16
  
  - CachedInputFileSystem.js:91 
    [frontend]/[enhanced-resolve]/lib/CachedInputFileSystem.js:91:9
  

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

[  Error: error:0308010C:digital envelope routines::unsupported
  
  - hash:67 new Hash
    node:internal/crypto/hash:67:19
  
  - node:crypto:130 Object.createHash
    node:crypto:130:10
  
  - createHash.js:135 module.exports
    [frontend]/[webpack]/lib/util/createHash.js:135:53
  
  - NormalModule.js:417 NormalModule._initBuildHash
    [frontend]/[webpack]/lib/NormalModule.js:417:16
  
  - NormalModule.js:471 handleParseError
    [frontend]/[webpack]/lib/NormalModule.js:471:10
  
  - NormalModule.js:503 
    [frontend]/[webpack]/lib/NormalModule.js:503:5
  
  - NormalModule.js:358 
    [frontend]/[webpack]/lib/NormalModule.js:358:12
  
  - LoaderRunner.js:373 
    [frontend]/[loader-runner]/lib/LoaderRunner.js:373:3
  
  - LoaderRunner.js:214 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:214:10
  
  - LoaderRunner.js:221 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:221:10
  
  - LoaderRunner.js:236 
    [frontend]/[loader-runner]/lib/LoaderRunner.js:236:3
  
  - LoaderRunner.js:111 Object.context.callback
    [frontend]/[loader-runner]/lib/LoaderRunner.js:111:13
  
  - loader.transform-quasar-imports.js:23 Object.module.exports
    [frontend]/[@quasar]/app/lib/webpack/loader.transform-quasar-imports.js:23:15
  
  - LoaderRunner.js:119 LOADER_EXECUTION
    [frontend]/[loader-runner]/lib/LoaderRunner.js:119:14
  
  - LoaderRunner.js:120 runSyncOrAsync
    [frontend]/[loader-runner]/lib/LoaderRunner.js:120:4
  
  - LoaderRunner.js:232 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:232:2
  
  - LoaderRunner.js:221 iterateNormalLoaders
    [frontend]/[loader-runner]/lib/LoaderRunner.js:221:10
  
  - LoaderRunner.js:236 
    [frontend]/[loader-runner]/lib/LoaderRunner.js:236:3
  
  - LoaderRunner.js:111 context.callback
    [frontend]/[loader-runner]/lib/LoaderRunner.js:111:13
  
  - index.js:44 
    [frontend]/[babel-loader]/lib/index.js:44:71
  
] {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I fixed it by changing the frontend docker image for build like that 
```
-FROM node:lts-alpine AS build
+FROM node:14 AS build
```

Not sure if you want a PR for this ?

**Comment by Zeecka** [comment] 2022-11-22 13:07
Duplicate of https://github.com/pwndoc/pwndoc/issues/383 , there is already a pending PR https://github.com/pwndoc/pwndoc/pull/384.

**Closed** 2023-03-02 15:06 UTC
